services:

    trinity.cache:
      class: Doctrine\Common\Cache\ApcuCache

    trinity.settings:
      class: Trinity\Bundle\SettingsBundle\Manager\SettingsManager
      lazy: true
      arguments:
        - "@doctrine"
        - "%settings_manager.settings%"
        - "@trinity.cache"

    trinity.settings.twig:
      class: Trinity\Bundle\SettingsBundle\Twig\SettingsExtension
      lazy: false
      arguments:
        - "@trinity.settings"
      public: false
      tags:
          - { name: twig.extension }
