language: php

php:
- '7.1'

before_script:
- phpenv config-add travis.ini
- if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then pecl config-set preferred_state beta; echo yes | pecl install -f apcu; fi;
- composer install

script:
- phpunit --coverage-clover build/logs/clover.xml

after_success:
- sh -c 'php vendor/bin/coveralls -v'

cache:
  directories:
  - $HOME/.composer/cache

notifications:
  hipchat:
    rooms:
      secure: yJZC41fMwdDKDfX37oGVSIPHSTDGn/syNyFB2jEPslaTSxxBh0s/yfOH2njXqMzKA6WaPrEwhjl/12e2SjWLVxnFnQgnfMnNzX8pZfk5JhfLq+P7upVKOg3X8aEiqmo9lR26kmStK3gI5MJmn2NRX/rqqLUETBSiDn7nyegfp7UTSBXrckE8uAEuuPCghvx/n3I/IWEqG25pVILLwujxALnAYwjbzjjHvE9ph4MQ88sHuEDLg8xnn43opXQFJKXZqV3w08ORJOimfcDdmjhowVDhfeR8ZnEwWtVBiI4o4ibA3ZrTfub60mr4xBxHN9J/b2cfHHU2VoGOQ/H+N1h6Gr7YgD5EpV2NNUFSvoDgsGNb0BuBJmfn8NcZa8rZVa8NOL1gsfQmWxDK2tf6yGLWPihsJkVi1aR1WqEyY0mWIZw/jcZs7Js9mD8et2D1Yn9hx9q5Ra9K4L8/0sJQkbg8R/TWibR8/XipOi9jfuQ3J8bBr7vVdGR4Yv+nmGgDIMM/MQqjBTKEyF7ldwX5tR8wFTa6CVv2kWyIdeDkgBx/6AlJeJEL6OiCpfEthcCSEYTRgbAbhkUpHVvKnloenRBMdN6MIw3qKdEs3j13aMCPPD+WkzCl8CpR0136DSLZorKKkYt1QeucsawzZwyw0Hs6rRS8NJbia/rWY4lIGUYr0+4=
